# Generated by Django 4.0 on 2021-12-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('send_email', 'Send_Email'), ('store_log', 'Store_Log'), ('create_task', 'Create_Task')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['action'], name='rules_action_d40bd9_idx'),
        ),
    ]
