# Generated by Django 4.0 on 2021-12-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_rule_action_rule_rules_action_d40bd9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_entity',
            field=models.CharField(default='customer', max_length=15),
        ),
    ]
