# Generated by Django 4.0 on 2021-12-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_task_created_by_task_task_created_entity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_data_si_0a88de_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by_task'], name='tasks_created_486944_idx'),
        ),
    ]
