# Generated by Django 4.0 on 2021-12-28 18:51

from django.db import migrations, models
import django.db.models.deletion
import fleetmanager.model_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer')),
            ],
            options={
                'db_table': 'vehicles',
            },
            bases=(models.Model, fleetmanager.model_helpers.BaseMethod),
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tires', models.JSONField(null=True)),
                ('battery_level', models.IntegerField(null=True)),
                ('fuel_level', models.IntegerField(null=True)),
                ('gps_position', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle')),
            ],
            options={
                'db_table': 'vehicles_status',
            },
            bases=(models.Model, fleetmanager.model_helpers.BaseMethod),
        ),
        migrations.AddIndex(
            model_name='vehiclestatus',
            index=models.Index(fields=['battery_level'], name='vehicles_st_battery_85cbde_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestatus',
            index=models.Index(fields=['fuel_level'], name='vehicles_st_fuel_le_b8fe03_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestatus',
            index=models.Index(fields=['created_on'], name='vehicles_st_created_33b1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestatus',
            index=models.Index(fields=['updated_at'], name='vehicles_st_updated_7e6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestatus',
            index=models.Index(fields=['vehicle_id'], name='vehicles_st_vehicle_0489c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner_id'], name='vehicles_owner_i_b73183_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_on'], name='vehicles_created_3afc06_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['updated_at'], name='vehicles_updated_a8b1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_license_b08e3c_idx'),
        ),
    ]
