# Generated by Django 4.0 on 2021-12-28 18:51

from django.db import migrations, models
import fleetmanager.model_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
            bases=(models.Model, fleetmanager.model_helpers.BaseMethod),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_address'], name='customers_email_a_521261_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='customers_first_n_887155_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='customers_last_na_f2324a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_on'], name='customers_created_30c5be_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='customers_updated_a69b42_idx'),
        ),
    ]
